# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CapitalFlowIntradayResponse.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'CapitalFlowIntradayResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!CapitalFlowIntradayResponse.proto\"\xad\x01\n\x1b\x43\x61pitalFlowIntradayResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12H\n\x12\x63\x61pital_flow_lines\x18\x02 \x03(\x0b\x32,.CapitalFlowIntradayResponse.CapitalFlowLine\x1a\x34\n\x0f\x43\x61pitalFlowLine\x12\x0e\n\x06inflow\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CapitalFlowIntradayResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPITALFLOWINTRADAYRESPONSE']._serialized_start=38
  _globals['_CAPITALFLOWINTRADAYRESPONSE']._serialized_end=211
  _globals['_CAPITALFLOWINTRADAYRESPONSE_CAPITALFLOWLINE']._serialized_start=159
  _globals['_CAPITALFLOWINTRADAYRESPONSE_CAPITALFLOWLINE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
